### ISSUE TITLE
Cloud functions

### ISSUE THREAD

**Issue by FiF0o** [FiF0o/poll-app#1]
Code is available on `service-workers` branch.
`"messaging/failed-serviceworker-registration"`.
Permission is granted however the next promise call to get the tokens seems to be broken when deployed.

On localhost, dashboard log:

```
Error: The uid must be a non-empty string with at most 128 characters. at FirebaseAuthError.Error (native) at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:25:28) at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:90:23) at FirebaseAuthRequestHandler.getAccountInfoByUid (/user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:183:35) at Auth.getUser (/user_code/node_modules/firebase-admin/lib/auth/auth.js:115:40) at /user_code/index.js:42:40 at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:35:20 at process._tickDomainCallback (internal/process/next_tick.js:129:7)
 Error: The uid must be a non-empty string with at most 128 characters.
    at FirebaseAuthError.Error (native)
    at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:25:28)
    at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:90:23)
    at FirebaseAuthRequestHandler.getAccountInfoByUid (/user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:183:35)
    at Auth.getUser (/user_code/node_modules/firebase-admin/lib/auth/auth.js:115:40)
    at /user_code/index.js:42:40
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:35:20
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by FiF0o** [comment]
fixed in[ this commit](https://github.com/FiF0o/poll-app/commit/d8450e6a4e7726511a607ba9900289c1b5e02481)
